fix(submit): Warn on Open PR
clabby/st pull request #18
Opened 2024-10-22 16:26 UTC by refcell

2024-10-22 16:26 UTC, refcell commented
## 📚 $\text{Stack Overview}$

Pulls submitted in this stack:
* #18 👈
* `main`

_This comment was automatically generated by [`st`](https://github.com/clabby/st)._

2024-10-22 18:04 UTC, clabby requested changes

2024-10-22 18:04 UTC, clabby commented on README.md
> +> \[!WARNING\]
Needs rebase

2024-10-22 18:04 UTC, clabby commented on src/subcommands/remote/submit.rs
> +        }
Can we extract this into a function on `StContext`? This could be useful for `st track` as well, to actually link branches with their remote PRs that were opened outside of `st`.

2024-10-24 15:45 UTC, clabby approved these changes

2024-10-24 15:45 UTC, merged