feat: Add label + assignee select in PR submission
clabby/st pull request #39
Opened 2024-11-04 17:08 UTC by clabby

## Overview

Adds two more selects to the PR submission process to select labels and assignees for the PR.

closes https://github.com/clabby/st/issues/36

2024-11-04 17:08 UTC, clabby commented
## 📚 $\text{Stack Overview}$

Pulls submitted in this stack:
* #39 👈
* `main`

_This comment was automatically generated by [`st`](https://github.com/clabby/st)._

2024-11-05 13:11 UTC, refcell approved these changes

2024-11-05 13:12 UTC, refcell commented on src/subcommands/remote/submit.rs
> +            .transpose()?;
Still think it would be cool if there was an environment variable or global setting that allowed you to automagically set a default assignee.

e.g. if I have `ST_DEFAULT_ASSIGNEE=refcell` set, `st` doesn't prompt me for an assignee here.

2024-11-05 13:15 UTC, refcell commented on src/subcommands/remote/submit.rs
> +            )
There's an issue here. Octocrab will error if it gets an empty vec. This should return `Option::None` if `selected_labels` is empty.

e.g. error response:
```
🐙 octocrab error: GitHub { source: GitHubError { documentation_url: Some("https://docs.github.com/rest/issues/labels#add-labels-to-an-issue"), errors: None, message: "Invalid request.\n\nNo subschema in \"anyOf\" matched.\nFor 'anyOf/0', {\"labels\"=>[]} is not an array.\nFor 'anyOf/1', {\"labels\"=>[]} is not an array.\n1 item required; only 0 were supplied.", status_code: 422 }, backtrace: <disabled> }
```

2024-11-05 13:16 UTC, refcell requested changes
One small bug, otherwise nice work

2024-11-05 13:16 UTC, refcell commented on src/subcommands/remote/submit.rs
> +            )
There's an issue here. Octocrab will error if it gets an empty vec. This should return `Option::None` if `selected_labels` is empty.

e.g. error response:
```
🐙 octocrab error: GitHub { source: GitHubError { documentation_url: Some("https://docs.github.com/rest/issues/labels#add-labels-to-an-issue"), errors: None, message: "Invalid request.\n\nNo subschema in \"anyOf\" matched.\nFor 'anyOf/0', {\"labels\"=>[]} is not an array.\nFor 'anyOf/1', {\"labels\"=>[]} is not an array.\n1 item required; only 0 were supplied.", status_code: 422 }, backtrace: <disabled> }
```

2025-03-13 05:41 UTC, closed without merging